### PR TITLE
ENG-2956 | Added more unit testing for core functions and bump up the code coverage

### PR DESCRIPTION
**Pull request by MohdRafiUddin**
* Added more unit testing for core functions that cover the file operations and HTTP calls for import, export, and delete operations.
*  Added more eslint rules and enable eslint check during the unit test run.
* Added jest code coverage and jest code coverage threshold bumper.
* Replaced few fs methods with fs-extra methods like fs.writeFileSync with fsExtra.outputFileSync.

### code coverage report:
```
-----------------------------|---------|----------|---------|---------|-------------------
File                         | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-----------------------------|---------|----------|---------|---------|-------------------
All files                    |     100 |    95.76 |     100 |     100 |
 constants                   |     100 |      100 |     100 |     100 |
  artifact.js                |     100 |      100 |     100 |     100 |
 core/commonResources        |     100 |       75 |     100 |     100 |
  createObjectDefinitions.js |     100 |      100 |     100 |     100 |
  createTransformations.js   |     100 |       70 |     100 |     100 | 39-43
 core/elements               |     100 |    97.42 |     100 |     100 |
  buildElementsFromDir.js    |     100 |      100 |     100 |     100 |
  createElements.js          |     100 |    94.34 |     100 |     100 | 94-98,146
  getElements.js             |     100 |      100 |     100 |     100 |
  getExtendedElements.js     |     100 |      100 |     100 |     100 |
  getPrivateElements.js      |     100 |      100 |     100 |     100 |
  importElements.js          |     100 |    96.88 |     100 |     100 | 43
  removeElement.js           |     100 |      100 |     100 |     100 |
  removeElements.js          |     100 |      100 |     100 |     100 |
  saveElements.js            |     100 |      100 |     100 |     100 |
 core/formulas               |     100 |      100 |     100 |     100 |
  buildFormulasFromDir.js    |     100 |      100 |     100 |     100 |
  createFormulas.js          |     100 |      100 |     100 |     100 |
  getFormulas.js             |     100 |      100 |     100 |     100 |
  importFormulas.js          |     100 |      100 |     100 |     100 |
  removeFormula.js           |     100 |      100 |     100 |     100 |
  removeFormulas.js          |     100 |      100 |     100 |     100 |
  saveFormulas.js            |     100 |      100 |     100 |     100 |
 core/vdrs                   |     100 |    92.45 |     100 |     100 |
  downloadVdrs.js            |     100 |      100 |     100 |     100 |
  exportVdrs.js              |     100 |      100 |     100 |     100 |
  getVdrNames.js             |     100 |      100 |     100 |     100 |
  getVdrs.js                 |     100 |      100 |     100 |     100 |
  readVdrsFromDir.js         |     100 |     81.4 |     100 |     100 | 15-39,50-87
  uploadMultipleVdrs.js      |     100 |      100 |     100 |     100 |
  upsertVdrs.js              |     100 |      100 |     100 |     100 |
 events                      |     100 |      100 |     100 |     100 |
  cancelled-job.js           |     100 |      100 |     100 |     100 |
  emitter.js                 |     100 |      100 |     100 |     100 |
 utils                       |     100 |      100 |     100 |     100 |
  authHeader.js              |     100 |      100 |     100 |     100 |
  baseUrl.js                 |     100 |      100 |     100 |     100 |
  getDataToExport.js         |     100 |      100 |     100 |     100 |
  getResourceName.js         |     100 |      100 |     100 |     100 |
  http.js                    |     100 |      100 |     100 |     100 |
  logger.js                  |     100 |      100 |     100 |     100 |
  quoteString.js             |     100 |      100 |     100 |     100 |
  readFile.js                |     100 |      100 |     100 |     100 |
  regex.js                   |     100 |      100 |     100 |     100 |
  saveTo.js                  |     100 |      100 |     100 |     100 |
-----------------------------|---------|----------|---------|---------|-------------------
Test Suites: 31 passed, 31 total
Tests:       146 passed, 146 total
Snapshots:   0 total
Time:        8.909 s
```

### CODE REVIEW

**Review by GiriNellore — COMMENTED** [review]
@MohdRafiUddin Great work!! One suggestion is to add github actions for this repo to run unit tests (deploy folder), and ignore the same folder under npmignore file to avoid packaging that.

**Comment by MohdRafiUddin** [comment]
> @MohdRafiUddin Great work!! One suggestion is to add github actions for this repo to run unit tests (deploy folder), and ignore the same folder under npmignore file to avoid packaging that.

@GiriNellore The github actions are already in place and ignored in .npmignore file. Also, the jest by default does the coverage check while running the unit test cases and fails to incase of code coverage threshold level goes down. I have updated the README.

**Review by GiriNellore — APPROVED** [review]

**Review by mukundbayyaram — APPROVED** [review]

**Review by venkat202 — APPROVED** [review]

**Comment by mukundbayyaram** [comment]
@MohdRafiUddin 
**nitpick:** Can you update the test commands in the readme?

**Comment by MohdRafiUddin** [comment]
> @MohdRafiUddin
> **nitpick:** Can you update the test commands in the readme?

I did already

**Pull request merged**
